services:
  - type: web
    name: e-recruitment
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn e_recruitment.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-*$1dq+1j2-!k^wt!y%=%7sb3l=$1=n)8d=3sb8amzmma4-x$1%
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_DATABASE
        fromService:
          name: e-recruitment-db
          type: database
          property: databaseName
      - key: DB_USERNAME
        fromService:
          name: e-recruitment-db
          type: database
          property: user
      - key: DB_PASSWORD
        fromService:
          name: e-recruitment-db
          type: database
          property: password
      - key: DB_HOST
        fromService:
          name: e-recruitment-db
          type: database
          property: host
      - key: DB_PORT
        fromService:
          name: e-recruitment-db
          type: database
          property: port
      - key: EMAIL_HOST_USER
        value: elddrops@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: jypvvocdvgakzcds  # Use the actual app password here
databases:
  - name: e-recruitment-db
    databaseName: e_recruitment_db
    user: root