# Generated by Django 5.2.4 on 2025-07-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('lga', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('permanent_address', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('working_experience', models.CharField(max_length=200)),
            ],
        ),
    ]
